### PR TITLE
Added data files for rendered images

### PR DESCRIPTION
**Pull request by ojha-aditya**
# Created pickle files corresponding to a repetitive pattern (#3)

## Linting
  - No new python files added. The existing ones lint perfectly.

## Contents
  - Pickle files corresponding to the images [cube_grid_top](https://ibb.co/Vm8Bjwz) and [cube_grid_side](https://ibb.co/LrxxZdd).
  - cube_grid_top_data.pkl and cube_grid_side_data.pkl have been added to Images folder.
  - As per data generation task #3

## Labels and Milestones
  -Label: Data; Milestone: Blender - Create Period Structure Data

## Reviewer
  - @avgagliardo or @iglesias-cardinale or anyone else if they are done with their reviews already.

### CODE REVIEW

**Comment by ojha-aditya** [comment]
The code used is the same as the one in Images folder already.

**Comment by iglesias-cardinale** [comment]
I'm happy to review this, but I've already done a review so if somebody else needs a review for the grade they should take it.

**Comment by dnxjay** [comment]
I can be assigned for being the reviewer!

**Comment by kylemasc917** [comment]
@dnxjay Ive added you as a reviewer for this request please do so as soon as possible,

**Comment by dnxjay** [comment]
> @dnxjay Ive added you as a reviewer for this request please do so as soon as possible,

will work on that right now

**Comment by dnxjay** [comment]
@kylemasc917 looks good to merge

**Comment by kylemasc917** [comment]
ok merging now

**Pull request merged**
