### PR TITLE
Cleaned up Image

### PR DESCRIPTION
**Pull request by jkblc**
# Cleaned up Image
  - Cleaned up image built from hex_img_data.pkl in a Jupyter file

## Linting
  - Yes

## Contents
  - data_analysis.ipynb to build cleaned up image from hex_img_data.pkl file. Uses a custom wrapper of load_pickle_data from preparation.py

## Labels and Milestones
  - Cleaned-up image

## Reviewer
  - one of the other members working on making the images from pkl

### CODE REVIEW

**Comment by Cosmos491** [comment]
The code is well-structured with proper docstrings and comments explaining the purpose of each block. However, here are few of my observations:
1. The error message in custom_load_pickle is printed but not raised, which could hide issues during debugging.
2. The try-except block around the main code catches errors but doesn’t provide detailed context or traceback for debugging. 
     Try this instead:
    except Exception as e:
            print(f"Error loading pickle data: {e}")
            raise  _# Re-raise the exception to ensure the issue is not silently ignored_
3. aspect='auto' might distort the image if height and width are significantly different. Use aspect='equal' to preserve the image's original proportions.

Please let me know if @jkblc you have any questions, or need any clarification regarding the same.

**Comment by jkblc** [comment]
I have adjusted the aspect to preserve original image. As far as raising the error, it will just return an empty graph

**Review by p-pxmpo — COMMENTED** [review]
- Error handling is good
- Comments are descriptive
- Written well and plot looks great!

The only thing I am confused about is load_pickle_data is not being utilized since you already have custom_load_pickle_data. are you intending to replace one or the other? If you dont intend to use it I suggest just removing "from preperation import load_pickle_data". Other than that code looks great!

**Comment by jkblc** [comment]
I have removed that line. That was a remnant of my unsuccessful effort to use the functions provided

**Review by p-pxmpo — APPROVED** [review]
Looks good, I approve.

**Comment by jkblc** [comment]
Ok, can you go ahead and merge. Then you can add your code to the file and I'll review your PR again

**Comment by p-pxmpo** [comment]
@kylemasc917 this is good to merge now

**Pull request merged**
