### PR TITLE
Create Shift_FFT_data.py

### PR DESCRIPTION
**Pull request by Priyanka-43**
For this assignment all pull requests going  forward should contain the following.

# Title
  - This Pull request contain preparation.py file to shift the FFT data

## Linting
  - Not done yet.

### CODE REVIEW

**Comment by kylemasc917** [comment]
@ubsuny/cp1-24 Does anyone want to volunteer to review this?

**Comment by zbpetersbuf** [comment]
ill volunteer for review

**Review by zbpetersbuf — CHANGES_REQUESTED** [review]
So this code needs to be in the preparation.py file that is in the main branch or repository, the one that Dr Thomay made in class, the one that has the 
def dummy() code and just that one at the moment.

**Comment by zbpetersbuf** [comment]
To do this you need to go back to your branch and open up the preparation.py in your codespace then copy past it in that already made file (called preparation.py) and only push that one, also if you do it soon you are not going to have to deal with merge conflicts (if you don't delete anything pre-existing in the file, meaning the defined dummy() function)

**Comment by Priyanka-43** [comment]
I am closing this pull request. I have created new one.

**Pull request closed without merging**
