### PR TITLE
A function that reads in the pickle files from the data collection task and returns a pandas DataFrame

### PR DESCRIPTION
**Pull request by dhamalakamal**
For this assignment all pull requests going  forward should contain the following (please delete the placeholder text and add your own description)

# Title
  - Write a function that reads in the pickle files from the data collection task and returns a pandas DataFrame. Generate a 2D index / column header with the actual dimensions of the object in the picture using the size marker or the fixed size set in the blender file

## Linting
  - Does your code lint? - Yes

## Contents
  - A function `load_pickle_data` to read pickle file from previous data collection task
  - pytest fixtures and unit test cases for the same method

## Labels and Milestones
  - Label: Python code 
  - Milestone: Read_pickle_file_from_data

## Reviewer
  - @laserlab @HeshamElsaman @avgagliardo 

Any further questions on formatting pull requests can be asked in the issues tab or on discord. 
This document can be changed at any time.

### CODE REVIEW

**Comment by kylemasc917** [comment]
@Tolani4 I've added you as reviewer for this request please do so as soon as possible.

**Comment by kylemasc917** [comment]
@ojha-aditya I've added you as a reviewer to this request please do so as soon as possible.

**Review by ojha-aditya — APPROVED** [review]
The files look fine, the tests run well, linting and unit testing both. Also, the pylint disable line has been removed which is fine as per @laserlab's instructions. I think it is good to merge @kylemasc917

**Comment by kylemasc917** [comment]
ok merging!

**Pull request merged**
