### PR TITLE
Remove Periodic Behavior

### PR DESCRIPTION
**Pull request by abruns123**
## Linting
  It Should lint

## Contents
I've added a set of functions to preparation and test_preparation that revolve around removing periodic behavior from an image after a fourier transform has been applied to the data.

## Reviewer
  Anyone may review

### CODE REVIEW

**Comment by kylemasc917** [comment]
@ojha-aditya Ive added you as a reviewer for this request please do so as soon as possible.

**Comment by abruns123** [comment]
@ojha-aditya 
Friendly reminder that you've been assigned to review this

**Review by ojha-aditya — CHANGES_REQUESTED** [review]
Tailing whitespace errors after line 171 in preparations.py and line 64 in test_preparations.py need to be removed and the branch needs to be synced with the current version of the repository using the update branch button. Can be merged after that.

**Comment by abruns123** [comment]
@ojha-aditya 
I fixed line 171.
Line 64 in test_preparation.py is someone else's code. Can't do much about that. 
Branch should be synced

**Comment by ojha-aditya** [comment]
Branch is still not synced but I updated that myself as it is late and people might need the code. You can still fix the pylint error even if it is someone else's code because everyone will get a pylint fail message otherwise. 

@kylemasc917 the rest looks good to merge.

**Comment by ojha-aditya** [comment]
Okay I removed the line pylint error myself as it is too close to the deadline. @kylemasc917 looks good to merge.

> @ojha-aditya I fixed line 171. Line 64 in test_preparation.py is someone else's code. Can't do much about that. Branch should be synced

**Review by ojha-aditya — APPROVED** [review]
Can be merged now. All linting errors have been removed.

**Comment by kylemasc917** [comment]
ok merging

**Pull request merged**
