### PR TITLE
Blender image (data) added

### PR DESCRIPTION
**Pull request by avgagliardo**
# Blender image (data) added

## Linting
This PR does not contain additional code contributions.

## Contents
In the /Images directory is a new file named "hex_img_data.pkl". 

This file was created by loading [hex.png](https://ibb.co/TcF7tpH) into a pandas dataframe, and then pickled with the pandas dataframe.pickle() method.

~~Included in the image is a blue 1x1 meter box for unit reference.~~

The individual hex cells are now 1x1 meter units.

## Labels and Milestones
  - Milestone set "Blender - Create Period Structure Data" 

## Reviewer
  - If @iglesias-cardinale has not done a review, this might be a good one since the tasks are related. Alternatively, @ojha-aditya may be a good candidate since he is also working on this milestone.

### CODE REVIEW

**Comment by avgagliardo** [comment]
Also if anyone has feedback on the image itself, [hex.png](https://ibb.co/MCv5tKM), I can incorporate it into another render. I have a ton of control over how the scene is presented so if for whatever reason something is annoying to deal with (dimensions, spacing, color, etc), it should not be difficult to work around.

**Comment by avgagliardo** [comment]
-updated the image so that the individual hex structures are 1x1 units.

-removed the unit reference

**Comment by kylemasc917** [comment]
@abruns123 Ive added you as reviewer please do so as soon as possible. @iglesias-cardinale feel free to review this as well but since you have already it is not necessary.

**Comment by avgagliardo** [comment]
@abruns123 this PR is ready if you still need a review

**Comment by abruns123** [comment]
Is there a way to directly look at the image output by the pkl file? I've verified that it doesn't cause any error with the load_pickle_data function in preparation but I'm not sure how to actually look at the image produced. The png looks fine.

**Comment by avgagliardo** [comment]
> Is there a way to directly look at the image output by the pkl file? I've verified that it doesn't cause any error with the load_pickle_data function in preparation but I'm not sure how to actually look at the image produced. The png looks fine.

You have to start googling this stuff or checking docs when you encounter issues, we are way over the deadline now.

[Check this out ](https://stackoverflow.com/questions/46107348/how-to-display-image-stored-in-pandas-dataframe)

**Comment by avgagliardo** [comment]
@iglesias-cardinale could you review this if you get a chance today?

**Comment by kylemasc917** [comment]
I agree. Please @iglesias-cardinale @abruns123 if one of you could expedite the review process as soon as possible so others can use the image file.

**Review by abruns123 — APPROVED** [review]
Works with the preparation code. From what I can tell the image works for the purpose of the project. Should be good to merge.

**Review by jkblc — APPROVED** [review]
Looks good, merging so we can use the data

**Pull request merged**
