### PR TITLE
2D fft / inverse fft calculating the actual frequency

### PR DESCRIPTION
**Pull request by zbpetersbuf**
## Linting
  - lints 100%

## Contents
  - contains functions for 2D fft / inverse fft calculating the actual frequency aswell as their unit tests
  - edited preperation.py and test_preperation.py

## Reviewer
  - don't really have a suggestion for a reviewer, mabye someone who wants to get their review task completed early

### CODE REVIEW

**Comment by zbpetersbuf** [comment]
a little confused on what a useful unit is for the frequency function

**Comment by kylemasc917** [comment]
@ubsuny/cp1-24 Does anyone want to review this?

**Comment by HeshamElsaman** [comment]
> @ubsuny/cp1-24 Does anyone want to review this?

I can do it tonight

**Comment by zbpetersbuf** [comment]
So it may need to be edited later which Ill do with no problem, because I don't understand what a useful unit is for the frequency for a 2d fft of an image, also my functions take in the image as an image and converts it to an array with np.array() since i am unsure how the images will be saved

**Comment by HeshamElsaman** [comment]
> So it may need to be edited later which Ill do with no problem, because I don't understand what a useful unit is for the frequency for a 2d fft of an image, also my functions take in the image as an image and converts it to an array with np.array() since i am unsure how the images will be saved

For the frequency part, I'm also not sure about it. I'm confused about it as well because my task of creating the fixtures should assume that they will be in a pandas dataframe format. I'm still trying to figure out how to do that without using timestamps since it doesn't make sense to me in this case. So, as I checked your code, that might be also a useful note for you as a first comment to make sure that the data are supposed to be in a pandas data frame format.

For the image part, from my experience in dealing with images, the library that I was familiar with deals with an image as a set of three matrices for R, G, and B scales. I'm not sure whether it's possible to combine them into one matrix. But yeah, I guess we'll need to make sure what format the images will be in.

**Comment by zbpetersbuf** [comment]
Ya so don't merge this until tomorrow when its due, ill have to take a look at what images look like to be sure about what I typed here

**Comment by HeshamElsaman** [comment]
Following up on our discussion, I guess I got a sense for the frequency now if we consider it to be cycles/pixel (considering the indexing (spacing) is in pixels)

Also, for the image format, I checked @iglesias-cardinale code as well, and I guess this is the library that I dealt with before (PTL). To the limit of my knowledge, using this library, the images are represented by a 2D array of 3D tubles for RGB images, or single-valued enteries for grayscale images.

**Comment by kylemasc917** [comment]
@HeshamElsaman Is this still good to merge or are more changes needed?

**Comment by iglesias-cardinale** [comment]
> the images are represented by a 2D array of 3D tubles for RGB images, or single-valued enteries for grayscale images.

This is basically my understanding as well. Each pixel (in an rgb image) is represented by a vector of length three. The elements of the vector are all between 0 and 255 and represent the intensity of red (min 0 max 255), intensity of green and intensity of blue. For a grayscale image it's the same thing except every pixel gets a single number that ranges from 0 (black) to 255 (white).

Grayscale is a lot easier to work with for the purposes of our task here, but we can easily convert from rgb to grayscale using ```Image.open('path/to/pic.png').convert('L')```

**Comment by zbpetersbuf** [comment]
My code is good to go

**Pull request merged**
