### PR TITLE
Data Presentation (Notebook file)

### PR DESCRIPTION
**Pull request by haiderabbas007**
# Data Presentation (Notebook file)

## Linting
  - Yes (10/10)

## Contents
 - This PR builds on the code written by **p-pxmpo** and **jkblc**.
 - Task Group 3 members were supposed to work on a **single** data analysis Jupyter notebook called data_analysis.ipynb
 - I combined the code written by the aforementioned people, corrected linting and functional errors, and made it operational as a single, cohesive and consistent unit that is able to generate the required images from the pickle files using functions from `preparation.py`.

## Reviewer
  - Suggested Reviewers: @Cosmos491 @p-pxmpo @jkblc @laserlab

### CODE REVIEW

**Comment by haiderabbas007** [comment]
@kylemasc917 any progress?

**Comment by haiderabbas007** [comment]
@SchrodingersStruggle

**Comment by kylemasc917** [comment]
@Cosmos491 @p-pxmpo @jkblc could one of you please review this asap.

**Comment by Cosmos491** [comment]
@haiderabbas007 I am confused about the file here, as I can see there are all the images generated. Could you elaborate on being more specific about the data file you chose and how did you go from there?

**Review by p-pxmpo — COMMENTED** [review]
@haiderabbas007 data_analysis.ipynb was merged from PR #36 I would suggest just creating a new PR and adding your code to that ipynb.

**Comment by haiderabbas007** [comment]
@p-pxmpo That would be inefficient I think. We (Task Group 3 members) were asked to work on a single notebook file. The `data_analysis.ipynb` that was approved only produces the cleaned up hexagonal image. It does not include the other two images, nor does it incorporate the plot with the original frequency information. Even if I create a new PR, I would have to remove all of the code in the existing file which was approved and replace it with mine for the thing to work and produce output images. Should I do that then?

**Comment by haiderabbas007** [comment]
> @haiderabbas007 I am confused about the file here, as I can see there are all the images generated. Could you elaborate on being more specific about the data file you chose and how did you go from there?

So I took all the pickle files in the images folder as the raw inputs, and generated the corresponding outputs. The cube side data file was used to plot the original frequency information with the removed part highlighted, and the rest were used to produce cleaned-up images. Hope that makes sense!

**Pull request closed without merging**
