### PR TITLE
Cleaning image (cube grid top)

### PR DESCRIPTION
**Pull request by Cosmos491**
1. This PR builds on the code written by haiderabbas007, p-pxmpo and jkblc.
2. Task Group 3 members were supposed to work on a single data analysis Jupyter notebook called data_analysis.ipynb
3. I have used the data from the image folder that contains the file "cube_grid_top_data.pkl".

Sugessted reviewer: @haiderabbas007 @jkblc

### CODE REVIEW

**Comment by haiderabbas007** [comment]
Only the cleaned-up image is needed, the original is not needed. Secondly, can you choose the same scale for both axes? The output image should be squarish.

**Comment by Cosmos491** [comment]
Thank you for the suggestions @haiderabbas007 . I have now made the desired changes.

**Comment by kylemasc917** [comment]
@haiderabbas007 If these are good please approve so they can be merged.

**Review by haiderabbas007 — APPROVED** [review]
Good job Ved

**Pull request merged**
