### PR TITLE
Original frequency plot and removed periodic frequencies plot

### PR DESCRIPTION
**Pull request by p-pxmpo**
For this assignment all pull requests going  forward should contain the following (please delete the placeholder text and add your own description)

# Title
  - Original frequency plot and removed periodic frequencies plot

## Linting
  - The code works with pylint

## Contents
  - This PR contains the file that plots the frequency spectrum of the cube_grid_top_data.pkl file and plots the frequency spectrum with the high frequency components being removed using the periodic_erase function.
  - The file is in a common jupyter notebook called data_analysis.ipynb. 

## Labels and Milestones
  - Plot frequency information

## Reviewer
  - @SchrodingersStruggle since they have been assigned the same task.

Any further questions on formatting pull requests can be asked in the issues tab or on discord. 
This document can be changed at any time.

### CODE REVIEW

**Comment by haiderabbas007** [comment]
Could you please clarify this?
image

**Comment by haiderabbas007** [comment]
> I can review this as requested.

Yes please, as I need this for my task.

**Comment by haiderabbas007** [comment]
This as well
image

**Review by SchrodingersStruggle — CHANGES_REQUESTED** [review]
Average and erase do not seem to be functions supported in the current requirements we have for the repository. You can either request the packages needed for these functions to be added to the requirements file, or change the functions into something which can be used by anyone.

**Comment by SchrodingersStruggle** [comment]
I would reference specific lines, but I'm not entirely sure how to do that in a Jupyter file.

**Comment by p-pxmpo** [comment]
Thank you for the review! those were functions defined in preperation.py in PR #30 but not merged into main by the time I created this PR. I will fix it today should be no later than 5PM.

**Comment by p-pxmpo** [comment]
> @SchrodingersStruggle Thank you for the review! those were functions defined in preperation.py in PR #30 but not merged into main by the time I created this PR. I will fix it today should be no later than 5PM.

Actually cancel that I will fix it right now

**Comment by p-pxmpo** [comment]
> > @SchrodingersStruggle Thank you for the review! those were functions defined in preperation.py in PR #30 but not merged into main by the time I created this PR. I will fix it today should be no later than 5PM.
> 
> Actually cancel that I will fix it right now

Code has been fixed now, ready to be merged

**Review by jkblc — CHANGES_REQUESTED** [review]
The required filename is data_analysis.ipynb

**Comment by kylemasc917** [comment]
Once one of the reviewers gives an approval ill merge

**Review by SchrodingersStruggle — COMMENTED** [review]
Looks good, especially now that dependancies are sorted.

**Review by SchrodingersStruggle — APPROVED** [review]

**Comment by kylemasc917** [comment]
You just need to resolve the last merge conflict and it should be ok to merge

**Comment by p-pxmpo** [comment]
@kylemasc917 merge conflict resolved

**Comment by p-pxmpo** [comment]
> @kylemasc917 merge conflict resolved

As soon as this PR gets merged I will add my code with the original data_analysis.ipynb that was added with PR #36

**Comment by p-pxmpo** [comment]
@kylemasc917 check PR #44

**Comment by kylemasc917** [comment]
ok feel free to close this

**Pull request closed without merging**
